POST http://localhost:3000/tecnicos
Content-Type: application/json

{
  "nome": "Carlos Técnico"
}

@baseURL = http://localhost:3000
@id_do_tecnico = 1

### Listar todos os técnicos
GET {{baseURL}}/tecnicos
Accept: application/json


### Criar um novo técnico
POST {{baseURL}}/tecnicos
Content-Type: application/json

{
  "nome": "Carlos Técnico"
}


### Criar outro técnico
POST {{baseURL}}/tecnicos
Content-Type: application/json

{
  "nome": "Ana Técnica"
}


### Criar técnico sem nome (erro esperado)
POST {{baseURL}}/tecnicos
Content-Type: application/json

{
}


### Atualizar um técnico existente (substitua @id_do_tecnico)
PUT {{baseURL}}/tecnicos/{{id_do_tecnico}}
Content-Type: application/json

{
  "nome": "Carlos Técnico Atualizado"
}


### Atualizar técnico inexistente (erro esperado)
PUT {{baseURL}}/tecnicos/9999
Content-Type: application/json

{
  "nome": "Técnico Inexistente"
}


### Deletar um técnico existente (substitua @id_do_tecnico)
DELETE {{baseURL}}/tecnicos/{{id_do_tecnico}}
Accept: application/json


### Deletar um técnico inexistente (erro esperado)
DELETE {{baseURL}}/tecnicos/9999
Accept: application/json
